/**
 * Уровень A1, раздел 1 «Первые шаги»: 5 уроков по 9 заданий.
 * Все тексты написаны для Otti и не взяты из других курсов.
 */
import type { Section } from "@/content/course/types";

export const a1Intro: Section = {
  id: "a1-intro",
  level: "A1",
  number: 1,
  title: "Первые шаги",
  description: "Знакомимся, рассказываем о себе, семье и своём дне.",
  lessons: [
    /* ───────────────────────────── Урок 1 ───────────────────────────── */
    {
      id: "a1-intro-l1",
      number: 1,
      title: "Приветствие и знакомство",
      description: "Здороваемся, представляемся и спрашиваем, как дела.",
      topic: "greetings",
      durationMin: 7,
      theory: {
        title: "Как поздороваться и представиться",
        blocks: [
          {
            kind: "text",
            text: "**Hello** — «здравствуйте» или «привет». **Hi** — только «привет», так говорят друзьям и ровесникам. На прощание — **Goodbye** или короче **Bye**.",
          },
          {
            kind: "text",
            text: "Чтобы представиться, скажи **My name is Anna** (дословно «моё имя — Анна») или просто **I'm Anna**. Спросить имя: **What's your name?**",
          },
          {
            kind: "table",
            headers: ["По-английски", "По-русски"],
            rows: [
              ["Good morning", "Доброе утро (до полудня)"],
              ["Good afternoon", "Добрый день"],
              ["Good evening", "Добрый вечер"],
              ["Nice to meet you!", "Приятно познакомиться!"],
              ["How are you?", "Как дела?"],
              ["I'm fine, thanks. And you?", "Хорошо, спасибо. А у тебя?"],
            ],
          },
          {
            kind: "tip",
            text: "**I'm** — это сокращение от **I am**, а **What's** — от **What is**. В разговоре почти всегда используют короткие формы.",
          },
        ],
      },
      words: [
        { en: "hello", ru: "привет, здравствуйте", example: "Hello, Mark!", exampleRu: "Здравствуй, Марк!" },
        { en: "hi", ru: "привет", example: "Hi! How are you?", exampleRu: "Привет! Как дела?" },
        { en: "goodbye", ru: "до свидания", example: "Goodbye, see you tomorrow!", exampleRu: "До свидания, увидимся завтра!" },
        { en: "name", ru: "имя", example: "My name is Olga.", exampleRu: "Меня зовут Ольга." },
        { en: "nice", ru: "приятный, милый", example: "Nice to meet you!", exampleRu: "Приятно познакомиться!" },
        { en: "meet", ru: "встречать, знакомиться", example: "I meet my friends on Friday.", exampleRu: "Я встречаюсь с друзьями в пятницу." },
        { en: "thanks", ru: "спасибо", example: "I'm fine, thanks.", exampleRu: "Хорошо, спасибо." },
        { en: "fine", ru: "хорошо (о самочувствии)", example: "I'm fine. And you?", exampleRu: "У меня всё хорошо. А у тебя?" },
      ],
      examples: [
        { en: "Hi! My name is Tom.", ru: "Привет! Меня зовут Том." },
        { en: "What's your name?", ru: "Как тебя зовут?" },
        { en: "Nice to meet you!", ru: "Приятно познакомиться!" },
        { en: "How are you? — I'm fine, thanks.", ru: "Как дела? — Хорошо, спасибо." },
      ],
      exercises: [
        {
          id: "a1-intro-l1-ex1",
          type: "choose-translation",
          topic: "greetings",
          skill: "vocabulary",
          prompt: "Выбери перевод",
          text: "Nice to meet you!",
          textLang: "en",
          options: ["Приятно познакомиться!", "Как тебя зовут?", "До свидания!", "Доброе утро!"],
          optionsLang: "ru",
          answer: 0,
          explanation: "Nice to meet you — фраза при знакомстве. Meet — «встречать, знакомиться».",
        },
        {
          id: "a1-intro-l1-ex2",
          type: "choose-word",
          topic: "greetings",
          skill: "vocabulary",
          prompt: "Выбери английское слово",
          text: "имя",
          textLang: "ru",
          options: ["name", "nice", "meet", "fine"],
          optionsLang: "en",
          answer: 0,
          explanation: "Name — «имя». My name is… — «Меня зовут…».",
        },
        {
          id: "a1-intro-l1-ex3",
          type: "match-pairs",
          topic: "greetings",
          skill: "vocabulary",
          prompt: "Соедини слово и перевод",
          pairs: [
            { en: "hello", ru: "привет" },
            { en: "goodbye", ru: "до свидания" },
            { en: "thanks", ru: "спасибо" },
            { en: "name", ru: "имя" },
          ],
          explanation: "Эти слова пригодятся в первом же разговоре на английском.",
        },
        {
          id: "a1-intro-l1-ex4",
          type: "fill-blank",
          topic: "greetings",
          skill: "vocabulary",
          prompt: "Впиши пропущенное слово",
          sentence: "My ___ is Anna.",
          accepted: ["name"],
          hint: "Слово «имя»",
          translation: "Меня зовут Анна.",
          explanation: "Дословно: «Моё имя — Анна». По-английски так и говорят: My name is…",
        },
        {
          id: "a1-intro-l1-ex5",
          type: "grammar-choice",
          topic: "greetings",
          skill: "grammar",
          prompt: "Выбери правильный вариант",
          text: "How ___ you?",
          textLang: "en",
          options: ["is", "are", "am"],
          optionsLang: "en",
          answer: 1,
          translation: "Как дела?",
          explanation: "Со словом you всегда используется are: How are you?",
        },
        {
          id: "a1-intro-l1-ex6",
          type: "build-sentence",
          topic: "greetings",
          skill: "word-order",
          prompt: "Собери предложение",
          source: "Меня зовут Том.",
          tiles: ["My", "name", "is", "Tom", "I"],
          accepted: ["My name is Tom"],
          explanation: "Порядок слов: My name is + имя. Слово I здесь лишнее.",
        },
        {
          id: "a1-intro-l1-ex7",
          type: "choose-translation",
          topic: "greetings",
          skill: "vocabulary",
          prompt: "Выбери перевод",
          text: "Good evening!",
          textLang: "en",
          options: ["Добрый вечер!", "Доброе утро!", "Спокойной ночи!", "Добрый день!"],
          optionsLang: "ru",
          answer: 0,
          explanation: "Evening — «вечер». Good morning — утром, good afternoon — днём, good evening — вечером.",
        },
        {
          id: "a1-intro-l1-ex8",
          type: "translate-phrase",
          topic: "greetings",
          skill: "translation",
          prompt: "Переведи на английский",
          source: "Доброе утро!",
          accepted: ["Good morning"],
          explanation: "Good morning — так здороваются до полудня.",
        },
        {
          id: "a1-intro-l1-ex9",
          type: "tutor-reply",
          topic: "greetings",
          skill: "speaking",
          prompt: "Представься Отти",
          question: "Hi! I'm Otti. What's your name?",
          questionTranslation: "Привет! Я Отти. Как тебя зовут?",
          patterns: [
            "^((hi|hello|hey) )?(otti )?(my name is|i am|name is) [\\p{L}-]+( [\\p{L}-]+)?( nice to meet you( too)?)?$",
          ],
          sample: "Hi, Otti! My name is Anna.",
          sampleTranslation: "Привет, Отти! Меня зовут Анна.",
          explanation: "Представиться можно двумя способами: My name is… или I'm…",
        },
      ],
    },

    /* ───────────────────────────── Урок 2 ───────────────────────────── */
    {
      id: "a1-intro-l2",
      number: 2,
      title: "Местоимения и глагол to be",
      description: "Я, ты, он, она… и главный глагол английского языка.",
      topic: "to-be",
      durationMin: 8,
      theory: {
        title: "Глагол to be: am, is, are",
        blocks: [
          {
            kind: "text",
            text: "По-русски мы говорим «Я студент» — без глагола. В английском глагол нужен всегда: **I am a student**. Этот глагол — **to be** («быть, являться»), и у него три формы: **am**, **is**, **are**.",
          },
          {
            kind: "table",
            headers: ["Кто", "Форма", "Коротко"],
            rows: [
              ["I — я", "am", "I'm"],
              ["you — ты, вы", "are", "you're"],
              ["he — он, she — она, it — оно, это", "is", "he's, she's, it's"],
              ["we — мы, they — они", "are", "we're, they're"],
            ],
          },
          {
            kind: "text",
            text: "Отрицание — добавляем **not**: **I am not tired**, **She is not (isn't) at home**. Вопрос — меняем местами: **Are you a student?** — **Yes, I am.** / **No, I'm not.**",
          },
          {
            kind: "tip",
            text: "Перед профессией в единственном числе ставим **a**: **She is a teacher**. Во множественном — не ставим: **They are teachers**.",
          },
        ],
      },
      words: [
        { en: "he", ru: "он", example: "He is my brother.", exampleRu: "Он мой брат." },
        { en: "she", ru: "она", example: "She is at home.", exampleRu: "Она дома." },
        { en: "we", ru: "мы", example: "We are friends.", exampleRu: "Мы друзья." },
        { en: "they", ru: "они", example: "They are from Kazan.", exampleRu: "Они из Казани." },
        { en: "student", ru: "студент", example: "I am a student.", exampleRu: "Я студент." },
        { en: "teacher", ru: "учитель", example: "My mother is a teacher.", exampleRu: "Моя мама — учитель." },
        { en: "friend", ru: "друг, подруга", example: "Kate is my friend.", exampleRu: "Катя — моя подруга." },
        { en: "happy", ru: "счастливый, довольный", example: "We are happy today.", exampleRu: "Сегодня мы счастливы." },
      ],
      examples: [
        { en: "I am a student.", ru: "Я студент." },
        { en: "She is my friend.", ru: "Она моя подруга." },
        { en: "We are happy.", ru: "Мы счастливы." },
        { en: "Are you a teacher? — No, I'm not.", ru: "Ты учитель? — Нет." },
      ],
      exercises: [
        {
          id: "a1-intro-l2-ex1",
          type: "grammar-choice",
          topic: "to-be",
          skill: "grammar",
          prompt: "Выбери правильную форму",
          text: "She ___ a teacher.",
          textLang: "en",
          options: ["am", "is", "are"],
          optionsLang: "en",
          answer: 1,
          translation: "Она учитель.",
          explanation: "С he, she и it используется is.",
        },
        {
          id: "a1-intro-l2-ex2",
          type: "grammar-choice",
          topic: "to-be",
          skill: "grammar",
          prompt: "Выбери правильную форму",
          text: "We ___ friends.",
          textLang: "en",
          options: ["is", "am", "are"],
          optionsLang: "en",
          answer: 2,
          translation: "Мы друзья.",
          explanation: "С we, you и they используется are.",
        },
        {
          id: "a1-intro-l2-ex3",
          type: "match-pairs",
          topic: "pronouns",
          skill: "vocabulary",
          prompt: "Соедини местоимение и перевод",
          pairs: [
            { en: "he", ru: "он" },
            { en: "she", ru: "она" },
            { en: "we", ru: "мы" },
            { en: "they", ru: "они" },
          ],
          explanation: "He — о мужчине, she — о женщине, they — о нескольких людях или предметах.",
        },
        {
          id: "a1-intro-l2-ex4",
          type: "fill-blank",
          topic: "to-be",
          skill: "grammar",
          prompt: "Впиши пропущенное слово",
          sentence: "I ___ a student.",
          accepted: ["am"],
          hint: "Форма to be для I",
          translation: "Я студент.",
          explanation: "С I всегда am. По-русски глагол пропускаем, по-английски — нет.",
        },
        {
          id: "a1-intro-l2-ex5",
          type: "choose-translation",
          topic: "to-be",
          skill: "vocabulary",
          prompt: "Выбери перевод",
          text: "They are happy.",
          textLang: "en",
          options: ["Они счастливы.", "Мы счастливы.", "Он счастлив.", "Они были счастливы."],
          optionsLang: "ru",
          answer: 0,
          explanation: "They — «они», are — форма to be в настоящем времени.",
        },
        {
          id: "a1-intro-l2-ex6",
          type: "build-sentence",
          topic: "to-be",
          skill: "word-order",
          prompt: "Собери предложение",
          source: "Он мой друг.",
          tiles: ["He", "is", "my", "friend", "are", "She"],
          accepted: ["He is my friend"],
          explanation: "С he нужна форма is: He is my friend.",
        },
        {
          id: "a1-intro-l2-ex7",
          type: "grammar-choice",
          topic: "to-be",
          skill: "grammar",
          prompt: "Выбери правильный вариант",
          text: "I ___ a teacher. I'm a student.",
          textLang: "en",
          options: ["am not", "is not", "are not"],
          optionsLang: "en",
          answer: 0,
          translation: "Я не учитель. Я студент.",
          explanation: "Отрицание с I: I am not (коротко I'm not).",
        },
        {
          id: "a1-intro-l2-ex8",
          type: "translate-phrase",
          topic: "to-be",
          skill: "translation",
          prompt: "Переведи на английский",
          source: "Мы студенты.",
          accepted: ["We are students"],
          explanation: "Мы — we, форма to be — are, студенты — students (множественное число: +s, без a).",
        },
        {
          id: "a1-intro-l2-ex9",
          type: "short-answer",
          topic: "to-be",
          skill: "speaking",
          prompt: "Ответь коротко по-английски: да или нет",
          question: "Are you a student?",
          questionTranslation: "Ты студент?",
          patterns: ["^(yes i am|no i am not)( a student)?$", "^i am( not)? a student$"],
          sample: "Yes, I am.",
          sampleTranslation: "Да.",
          explanation: "На вопрос Are you…? отвечают коротко: Yes, I am. / No, I'm not. Просто Yes, I'm — так не говорят.",
        },
      ],
    },

    /* ───────────────────────────── Урок 3 ───────────────────────────── */
    {
      id: "a1-intro-l3",
      number: 3,
      title: "Числа, возраст и страны",
      description: "Считаем до двадцати, говорим о возрасте и о том, откуда мы.",
      topic: "numbers",
      durationMin: 8,
      theory: {
        title: "Числа, возраст и страны",
        blocks: [
          {
            kind: "table",
            headers: ["Число", "По-английски"],
            rows: [
              ["1, 2, 3, 4, 5", "one, two, three, four, five"],
              ["6, 7, 8, 9, 10", "six, seven, eight, nine, ten"],
              ["11, 12", "eleven, twelve"],
              ["13–19", "thirteen, fourteen, fifteen … nineteen (окончание -teen)"],
              ["20, 30, 40, 50", "twenty, thirty, forty, fifty (окончание -ty)"],
            ],
          },
          {
            kind: "text",
            text: "Возраст называем через глагол to be: **I am 20** или **I am 20 years old**. Спросить: **How old are you?** Сказать «I have 20 years» — ошибка.",
          },
          {
            kind: "text",
            text: "Откуда ты? — **Where are you from?** Ответ: **I'm from Russia**. Названия стран и национальностей пишутся с большой буквы: **Germany — German**, **France — French**, **China — Chinese**.",
          },
          {
            kind: "tip",
            text: "Не путай **fifteen** (15) и **fifty** (50): в -teen ударение в конце, в -ty — в начале.",
          },
        ],
      },
      words: [
        { en: "number", ru: "число, номер", example: "What's your phone number?", exampleRu: "Какой у тебя номер телефона?" },
        { en: "twenty", ru: "двадцать", example: "She is twenty.", exampleRu: "Ей двадцать." },
        { en: "old", ru: "старый; о возрасте — «лет»", example: "I'm nineteen years old.", exampleRu: "Мне девятнадцать лет." },
        { en: "year", ru: "год", example: "This year I study English.", exampleRu: "В этом году я учу английский." },
        { en: "country", ru: "страна", example: "Russia is a big country.", exampleRu: "Россия — большая страна." },
        { en: "from", ru: "из, от", example: "I'm from Omsk.", exampleRu: "Я из Омска." },
        { en: "Russian", ru: "русский, российский", example: "I speak Russian.", exampleRu: "Я говорю по-русски." },
        { en: "where", ru: "где, откуда", example: "Where are you from?", exampleRu: "Откуда ты?" },
      ],
      examples: [
        { en: "I'm nineteen years old.", ru: "Мне девятнадцать лет." },
        { en: "How old are you?", ru: "Сколько тебе лет?" },
        { en: "Where are you from? — I'm from Russia.", ru: "Откуда ты? — Я из России." },
        { en: "She is from Germany. She is German.", ru: "Она из Германии. Она немка." },
      ],
      exercises: [
        {
          id: "a1-intro-l3-ex1",
          type: "choose-word",
          topic: "numbers",
          skill: "vocabulary",
          prompt: "Выбери английское слово",
          text: "пятнадцать",
          textLang: "ru",
          options: ["fifteen", "fifty", "five", "fourteen"],
          optionsLang: "en",
          answer: 0,
          explanation: "15 — fifteen (окончание -teen), 50 — fifty (окончание -ty).",
        },
        {
          id: "a1-intro-l3-ex2",
          type: "match-pairs",
          topic: "numbers",
          skill: "vocabulary",
          prompt: "Соедини число и перевод",
          pairs: [
            { en: "three", ru: "три" },
            { en: "eight", ru: "восемь" },
            { en: "twelve", ru: "двенадцать" },
            { en: "twenty", ru: "двадцать" },
          ],
          explanation: "Числа от 13 до 19 заканчиваются на -teen, а 12 — особое слово twelve.",
        },
        {
          id: "a1-intro-l3-ex3",
          type: "grammar-choice",
          topic: "age",
          skill: "grammar",
          prompt: "Выбери правильный вариант",
          text: "I ___ 20 years old.",
          textLang: "en",
          options: ["have", "am", "is"],
          optionsLang: "en",
          answer: 1,
          translation: "Мне 20 лет.",
          explanation: "Возраст называем через to be: I am 20. Сказать I have 20 years нельзя.",
        },
        {
          id: "a1-intro-l3-ex4",
          type: "choose-translation",
          topic: "countries",
          skill: "vocabulary",
          prompt: "Выбери перевод",
          text: "Where are you from?",
          textLang: "en",
          options: ["Откуда ты?", "Где ты живёшь?", "Куда ты идёшь?", "Как у тебя дела?"],
          optionsLang: "ru",
          answer: 0,
          explanation: "Where are you from? — дословно «Где ты из?». Так спрашивают, откуда человек.",
        },
        {
          id: "a1-intro-l3-ex5",
          type: "fill-blank",
          topic: "countries",
          skill: "grammar",
          prompt: "Впиши пропущенное слово",
          sentence: "I am ___ Russia.",
          accepted: ["from"],
          hint: "Предлог «из»",
          translation: "Я из России.",
          explanation: "«Из какой-то страны» — from: I'm from Russia.",
        },
        {
          id: "a1-intro-l3-ex6",
          type: "build-sentence",
          topic: "age",
          skill: "word-order",
          prompt: "Собери вопрос",
          source: "Сколько тебе лет?",
          tiles: ["How", "old", "are", "you", "is", "years"],
          accepted: ["How old are you"],
          explanation: "Вопрос о возрасте: How old are you? — дословно «Насколько ты старый?».",
        },
        {
          id: "a1-intro-l3-ex7",
          type: "grammar-choice",
          topic: "countries",
          skill: "vocabulary",
          prompt: "Выбери подходящее слово",
          text: "He is from France. He is ___.",
          textLang: "en",
          options: ["French", "France", "English"],
          optionsLang: "en",
          answer: 0,
          translation: "Он из Франции. Он француз.",
          explanation: "Страна — France, национальность — French. Оба слова пишутся с большой буквы.",
        },
        {
          id: "a1-intro-l3-ex8",
          type: "translate-phrase",
          topic: "age",
          skill: "translation",
          prompt: "Переведи на английский",
          source: "Мне восемнадцать лет.",
          accepted: ["I am eighteen", "I am eighteen years old", "I am 18", "I am 18 years old"],
          explanation: "Возраст — через am: I'm eighteen (years old).",
        },
        {
          id: "a1-intro-l3-ex9",
          type: "tutor-reply",
          topic: "countries",
          skill: "speaking",
          prompt: "Расскажи Отти, откуда ты",
          question: "Nice to meet you! Where are you from?",
          questionTranslation: "Приятно познакомиться! Откуда ты?",
          patterns: [
            "^((nice to meet you( too)?|hi|hello) )?(i am )?from [\\p{L}' -]+$",
            "^((nice to meet you( too)?|hi|hello) )?i live in [\\p{L}' -]+$",
          ],
          sample: "I'm from Russia.",
          sampleTranslation: "Я из России.",
          explanation: "Ответ строится так: I'm from + страна или город.",
        },
      ],
    },

    /* ───────────────────────────── Урок 4 ───────────────────────────── */
    {
      id: "a1-intro-l4",
      number: 4,
      title: "Семья",
      description: "Рассказываем о родных: мама, брат, сестра и «у меня есть».",
      topic: "family",
      durationMin: 8,
      theory: {
        title: "Семья, have / has и слова my, his, her",
        blocks: [
          {
            kind: "text",
            text: "«У меня есть» по-английски — **I have**: **I have a sister**. С he, she, it — **has**: **She has two brothers**.",
          },
          {
            kind: "table",
            headers: ["Кто", "Чей"],
            rows: [
              ["I — я", "my — мой"],
              ["you — ты, вы", "your — твой, ваш"],
              ["he — он", "his — его"],
              ["she — она", "her — её"],
              ["we — мы", "our — наш"],
              ["they — они", "their — их"],
            ],
          },
          {
            kind: "text",
            text: "Если говорим о брате Тома — **his brother**, о брате Анны — **her brother**. Род зависит от владельца, а не от брата.",
          },
          {
            kind: "tip",
            text: "Спросить про братьев и сестёр: **Do you have any brothers or sisters?** Ответ: **Yes, I have a sister.** или **No, I don't.**",
          },
        ],
      },
      words: [
        { en: "mother", ru: "мать, мама", example: "My mother is a doctor.", exampleRu: "Моя мама — врач." },
        { en: "father", ru: "отец, папа", example: "His father works in Moscow.", exampleRu: "Его папа работает в Москве." },
        { en: "parents", ru: "родители", example: "My parents live in Samara.", exampleRu: "Мои родители живут в Самаре." },
        { en: "brother", ru: "брат", example: "I have a brother.", exampleRu: "У меня есть брат." },
        { en: "sister", ru: "сестра", example: "Her sister is ten.", exampleRu: "Её сестре десять лет." },
        { en: "son", ru: "сын", example: "They have a son.", exampleRu: "У них есть сын." },
        { en: "daughter", ru: "дочь", example: "Our daughter is a student.", exampleRu: "Наша дочь — студентка." },
        { en: "family", ru: "семья", example: "This is my family.", exampleRu: "Это моя семья." },
      ],
      examples: [
        { en: "This is my family.", ru: "Это моя семья." },
        { en: "I have a sister.", ru: "У меня есть сестра." },
        { en: "Her brother is a teacher.", ru: "Её брат — учитель." },
        { en: "My parents are from Kazan.", ru: "Мои родители из Казани." },
      ],
      exercises: [
        {
          id: "a1-intro-l4-ex1",
          type: "match-pairs",
          topic: "family",
          skill: "vocabulary",
          prompt: "Соедини слово и перевод",
          pairs: [
            { en: "mother", ru: "мама" },
            { en: "father", ru: "папа" },
            { en: "sister", ru: "сестра" },
            { en: "brother", ru: "брат" },
          ],
          explanation: "Mother и father — нейтральные слова. В разговоре чаще говорят mom и dad.",
        },
        {
          id: "a1-intro-l4-ex2",
          type: "choose-word",
          topic: "family",
          skill: "vocabulary",
          prompt: "Выбери английское слово",
          text: "дочь",
          textLang: "ru",
          options: ["daughter", "son", "sister", "mother"],
          optionsLang: "en",
          answer: 0,
          explanation: "Daughter — «дочь», son — «сын».",
        },
        {
          id: "a1-intro-l4-ex3",
          type: "grammar-choice",
          topic: "have-has",
          skill: "grammar",
          prompt: "Выбери правильную форму",
          text: "She ___ two brothers.",
          textLang: "en",
          options: ["have", "has", "is"],
          optionsLang: "en",
          answer: 1,
          translation: "У неё два брата.",
          explanation: "С he, she, it — has, со всеми остальными — have.",
        },
        {
          id: "a1-intro-l4-ex4",
          type: "grammar-choice",
          topic: "possessives",
          skill: "grammar",
          prompt: "Выбери правильное слово",
          text: "This is Tom. ___ sister is a student.",
          textLang: "en",
          options: ["His", "Her", "Its"],
          optionsLang: "en",
          answer: 0,
          translation: "Это Том. Его сестра — студентка.",
          explanation: "Сестра Тома — his sister. His — «его» (о мужчине), her — «её».",
        },
        {
          id: "a1-intro-l4-ex5",
          type: "fill-blank",
          topic: "have-has",
          skill: "grammar",
          prompt: "Впиши пропущенное слово",
          sentence: "I ___ a brother.",
          accepted: ["have"],
          hint: "«У меня есть» — I …",
          translation: "У меня есть брат.",
          explanation: "«У меня есть» по-английски — I have.",
        },
        {
          id: "a1-intro-l4-ex6",
          type: "choose-translation",
          topic: "family",
          skill: "vocabulary",
          prompt: "Выбери перевод",
          text: "My parents are from Kazan.",
          textLang: "en",
          options: [
            "Мои родители из Казани.",
            "Мои родители в Казани.",
            "Мой отец из Казани.",
            "Мои друзья из Казани.",
          ],
          optionsLang: "ru",
          answer: 0,
          explanation: "Parents — «родители» (это не «родственники»!), from — «из».",
        },
        {
          id: "a1-intro-l4-ex7",
          type: "build-sentence",
          topic: "family",
          skill: "word-order",
          prompt: "Собери предложение",
          source: "Это моя семья.",
          tiles: ["This", "is", "my", "family", "are", "me"],
          accepted: ["This is my family"],
          explanation: "«Это…» — This is…; «моя семья» — my family.",
        },
        {
          id: "a1-intro-l4-ex8",
          type: "translate-phrase",
          topic: "have-has",
          skill: "translation",
          prompt: "Переведи на английский",
          source: "У неё есть сын.",
          accepted: ["She has a son", "She has got a son", "She's got a son"],
          explanation: "С she используется has: She has a son.",
        },
        {
          id: "a1-intro-l4-ex9",
          type: "short-answer",
          topic: "family",
          skill: "speaking",
          prompt: "Ответь одним предложением о своей семье",
          question: "Do you have any brothers or sisters?",
          questionTranslation: "У тебя есть братья или сёстры?",
          patterns: [
            "^(yes |no )?i (have|have got|do not have|have no)( a| an| one| two| three| four| five| any| no)? ?(brothers?|sisters?)( and (a |an |one |two |three )?(brothers?|sisters?))?$",
            "^(yes i do|no i do not)( have any brothers or sisters)?$",
          ],
          sample: "Yes, I have a sister.",
          sampleTranslation: "Да, у меня есть сестра.",
          explanation: "Отвечаем через have: Yes, I have a brother. Если нет — No, I don't.",
        },
      ],
    },

    /* ───────────────────────────── Урок 5 ───────────────────────────── */
    {
      id: "a1-intro-l5",
      number: 5,
      title: "Повседневные действия",
      description: "Рассказываем, что делаем каждый день: время Present Simple.",
      topic: "present-simple",
      durationMin: 9,
      theory: {
        title: "Present Simple: то, что мы делаем обычно",
        blocks: [
          {
            kind: "text",
            text: "О привычках и том, что происходит регулярно, говорим во времени **Present Simple**: **I get up at seven**, **We study English**.",
          },
          {
            kind: "text",
            text: "С he, she, it к глаголу добавляем **-s**: **She works**, **He reads**. Это самая частая ошибка — не забывай про -s!",
          },
          {
            kind: "table",
            headers: ["", "I, you, we, they", "he, she, it"],
            rows: [
              ["Утверждение", "I work", "She works"],
              ["Отрицание", "I don't work", "She doesn't work"],
              ["Вопрос", "Do you work?", "Does she work?"],
            ],
          },
          {
            kind: "tip",
            text: "В отрицании и вопросе -s «переезжает» в does, а глагол остаётся без -s: **She doesn't work**, а не «She doesn't works».",
          },
        ],
      },
      words: [
        { en: "get up", ru: "вставать", example: "I get up at seven.", exampleRu: "Я встаю в семь." },
        { en: "breakfast", ru: "завтрак", example: "We have breakfast at eight.", exampleRu: "Мы завтракаем в восемь." },
        { en: "work", ru: "работать; работа", example: "She works in a bank.", exampleRu: "Она работает в банке." },
        { en: "study", ru: "учиться, изучать", example: "I study English every day.", exampleRu: "Я учу английский каждый день." },
        { en: "go", ru: "идти, ехать", example: "They go to school.", exampleRu: "Они ходят в школу." },
        { en: "read", ru: "читать", example: "He reads books in the evening.", exampleRu: "Он читает книги вечером." },
        { en: "sleep", ru: "спать", example: "Cats sleep a lot.", exampleRu: "Кошки много спят." },
        { en: "every day", ru: "каждый день", example: "I walk my dog every day.", exampleRu: "Я гуляю с собакой каждый день." },
      ],
      examples: [
        { en: "I get up at seven.", ru: "Я встаю в семь." },
        { en: "She works in an office.", ru: "Она работает в офисе." },
        { en: "Do you study English every day?", ru: "Ты учишь английский каждый день?" },
        { en: "He doesn't drink coffee.", ru: "Он не пьёт кофе." },
      ],
      exercises: [
        {
          id: "a1-intro-l5-ex1",
          type: "match-pairs",
          topic: "daily-routine",
          skill: "vocabulary",
          prompt: "Соедини слово и перевод",
          pairs: [
            { en: "get up", ru: "вставать" },
            { en: "sleep", ru: "спать" },
            { en: "read", ru: "читать" },
            { en: "work", ru: "работать" },
          ],
          explanation: "Get up — это одно действие из двух слов: «вставать (с кровати)».",
        },
        {
          id: "a1-intro-l5-ex2",
          type: "grammar-choice",
          topic: "present-simple",
          skill: "grammar",
          prompt: "Выбери правильную форму",
          text: "She ___ in a bank.",
          textLang: "en",
          options: ["work", "works", "working"],
          optionsLang: "en",
          answer: 1,
          translation: "Она работает в банке.",
          explanation: "С she в Present Simple к глаголу добавляется -s: works.",
        },
        {
          id: "a1-intro-l5-ex3",
          type: "grammar-choice",
          topic: "present-simple",
          skill: "grammar",
          prompt: "Выбери правильный вариант",
          text: "I ___ like coffee.",
          textLang: "en",
          options: ["don't", "doesn't", "not"],
          optionsLang: "en",
          answer: 0,
          translation: "Я не люблю кофе.",
          explanation: "Отрицание с I — don't (do not). Doesn't — только с he, she, it.",
        },
        {
          id: "a1-intro-l5-ex4",
          type: "choose-translation",
          topic: "daily-routine",
          skill: "vocabulary",
          prompt: "Выбери перевод",
          text: "I get up at seven.",
          textLang: "en",
          options: ["Я встаю в семь.", "Я ложусь спать в семь.", "Я встал в семь.", "Мне семь лет."],
          optionsLang: "ru",
          answer: 0,
          explanation: "Get up — «вставать». Present Simple — действие, которое повторяется.",
        },
        {
          id: "a1-intro-l5-ex5",
          type: "fill-blank",
          topic: "present-simple",
          skill: "grammar",
          prompt: "Впиши пропущенное слово",
          sentence: "___ you study English every day?",
          accepted: ["do"],
          hint: "Вспомогательный глагол для you",
          translation: "Ты учишь английский каждый день?",
          explanation: "Вопрос в Present Simple начинается с Do. С he, she, it — с Does.",
        },
        {
          id: "a1-intro-l5-ex6",
          type: "build-sentence",
          topic: "present-simple",
          skill: "word-order",
          prompt: "Собери предложение",
          source: "Он читает каждый день.",
          tiles: ["He", "reads", "every", "day", "read", "is"],
          accepted: ["He reads every day"],
          explanation: "С he глагол получает -s: reads. Слово is здесь не нужно.",
        },
        {
          id: "a1-intro-l5-ex7",
          type: "choose-word",
          topic: "daily-routine",
          skill: "vocabulary",
          prompt: "Выбери английское слово",
          text: "завтрак",
          textLang: "ru",
          options: ["breakfast", "lunch", "dinner", "bread"],
          optionsLang: "en",
          answer: 0,
          explanation: "Breakfast — завтрак, lunch — обед, dinner — ужин.",
        },
        {
          id: "a1-intro-l5-ex8",
          type: "translate-phrase",
          topic: "present-simple",
          skill: "translation",
          prompt: "Переведи на английский",
          source: "Я работаю каждый день.",
          accepted: ["I work every day", "Every day I work"],
          explanation: "Present Simple с I — глагол без изменений: I work. «Каждый день» — every day.",
        },
        {
          id: "a1-intro-l5-ex9",
          type: "tutor-reply",
          topic: "daily-routine",
          skill: "speaking",
          prompt: "Расскажи Отти одним предложением, что ты делаешь утром",
          question: "What do you usually do in the morning?",
          questionTranslation: "Что ты обычно делаешь утром?",
          patterns: [
            "^(in the morning )?i (usually |always |often |sometimes )?(get up|wake up|have|drink|eat|go|read|run|work|study|take|make|do|walk|cook|listen|watch|brush|wash|check|feed|play|write)\\b[\\p{L}\\p{N}' -]*$",
          ],
          sample: "I usually get up at seven and have breakfast.",
          sampleTranslation: "Обычно я встаю в семь и завтракаю.",
          explanation: "О привычках говорим в Present Simple: I get up…, I have breakfast…",
        },
      ],
    },
  ],
};
